### PR TITLE
ENH: Using versioneer for automatic version information from VCS.

### LINKED ISSUE #10: Switch to use versioneer for automated version numbers.
As of now the version is hardcoded at the setup.py.
With https://github.com/warner/python-versioneer we can grab the version string from the VCS and use it.
I can work on that if it is of interest.

### PR DESCRIPTION
**Pull request by hhslepicka**
This closes #10 .

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]
Interesting approach, I was wondering how you'd handle the double module situation here. It looks like you opted to stuff all the versioneer stuff into the psp module and ignore the pyca blob, which makes total sense with how versioneer works.

**Comment by hhslepicka** [comment]
I decided that based on my understanding that `psp` is the "user facing" API? (Maybe I am wrong in here) ? And on the fact that the documentation was retrieving the version from psp...
I could not successfully run the tests on my machine but we can talk about it later offline. I am probably doing something wrong.

**Comment by ZLLentz** [comment]
`psp` is the user-facing api. This library is a bit confusing in this regard, it is called `pyca` because that is the name that everyone recognizes but most of our code that relies on this imports from `psp`

**Comment by hhslepicka** [comment]
Got it! Feel free to merge this PR. Thank you for all the explanation.

**Pull request merged**
